apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout-service
  template:
    metadata:
      labels:
        app: checkout-service
    spec:
      containers:
        - name: checkout-service
          image: 039612866426.dkr.ecr.ap-south-1.amazonaws.com/checkoutsvc:latest
          ports:
            - containerPort: 9094
          env:
            - name: JDBC_USER
              valueFrom:
                configMapKeyRef:
                  name: product-service-config
                  key: JDBC_USER
            - name: JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-service-secret
                  key: JDBC_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: checkout-service
  namespace: default
spec:
  selector:
    app: checkout-service
  ports:
    - protocol: TCP
      port: 9094
      targetPort: 9094
  type: ClusterIP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: checkout-service
spec:
  hosts:
    - "*"
  gateways:
    - istio-ingressgateway
  http:
    - match:
        - uri:
            prefix: /cart
        - uri:
            prefix: /shipping
        - uri:
            prefix: /order
        - uri:
            prefix: /wishlist
      route:
        - destination:
            host: checkout-service.default.svc.cluster.local
            port:
              number: 9094
